# Generated by Django 5.2.7 on 2025-11-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('PERMANENTE', 'Permanente'), ('TEMPORAL', 'Temporal')], max_length=20, verbose_name='Tipo de entrega')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de devolución')),
                ('estado_carta', models.CharField(choices=[('FIRMADA', 'Firmada'), ('PENDIENTE', 'Pendiente'), ('NO_APLICA', 'No Aplica')], default='PENDIENTE', max_length=20, verbose_name='Estado de carta')),
                ('estado_asignacion', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20, verbose_name='Estado de asignación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jefatura_solicitante', models.CharField(max_length=200, verbose_name='Jefatura solicitante')),
                ('tipo_dispositivo', models.CharField(max_length=20, verbose_name='Tipo de dispositivo')),
                ('justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de devolución')),
                ('estado_dispositivo', models.CharField(choices=[('OPTIMO', 'Óptimo'), ('CON_DANOS', 'Con Daños'), ('NO_FUNCIONAL', 'No Funcional')], max_length=20, verbose_name='Estado del dispositivo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_devolucion'],
            },
        ),
    ]
