# Generated by Django 5.2.7 on 2025-12-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='motivo',
            field=models.CharField(choices=[('CAMBIO', 'Cambio'), ('NUEVA_ENTREGA', 'Nueva entrega'), ('ROBO', 'Robo'), ('PRACTICA', 'Práctica')], default='NUEVA_ENTREGA', max_length=20, verbose_name='Motivo de solicitud'),
        ),
        migrations.AddField(
            model_name='request',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='branches.branch', verbose_name='Sucursal'),
        ),
    ]
