# Generated by Django (manual)

from django.db import migrations


def migrate_request_estados(apps, schema_editor):
    """
    Migra estados de solicitudes:
    - APROBADA → PENDIENTE (pueden ser asignadas)
    - RECHAZADA → ELIMINAR (decisión del usuario)
    """
    Request = apps.get_model('assignments', 'Request')

    # 1. Migrar APROBADA a PENDIENTE
    aprobadas = Request.objects.filter(estado='APROBADA')
    count_aprobadas = aprobadas.count()
    aprobadas.update(estado='PENDIENTE')

    # 2. Eliminar RECHAZADAS
    rechazadas = Request.objects.filter(estado='RECHAZADA')
    count_rechazadas = rechazadas.count()
    rechazadas.delete()

    print(f"✓ Migradas {count_aprobadas} solicitudes APROBADAS → PENDIENTE")
    print(f"✓ Eliminadas {count_rechazadas} solicitudes RECHAZADAS")


def reverse_migration(apps, schema_editor):
    """
    Reversión no posible - datos eliminados no se pueden recuperar.
    Se marca como irreversible.
    """
    raise RuntimeError("Esta migración no es reversible - los datos RECHAZADOS fueron eliminados")


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_request_motivo_request_sucursal'),
    ]

    operations = [
        migrations.RunPython(migrate_request_estados, reverse_migration),
    ]
