# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_simplify_request_estados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='estado',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('PENDIENTE', 'Pendiente'),
                    ('COMPLETADA', 'Completada'),
                ],
                default='PENDIENTE',
                verbose_name='Estado'
            ),
        ),
    ]
