# Generated by Django 5.2.7 on 2025-12-20 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_update_request_estado_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de firma de carta'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='firmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_firmadas', to=settings.AUTH_USER_MODEL, verbose_name='Firmado por'),
        ),
    ]
