# Generated by Django 5.2.7 on 2025-12-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_fecha_firma_assignment_firmado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='discount_data',
            field=models.JSONField(blank=True, help_text='Almacena información del descuento (monto, cuotas, mes primera cuota)', null=True, verbose_name='Datos de descuento'),
        ),
    ]
