# Generated by Django 5.2.7 on 2025-12-27 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_assignment_discount_data'),
        ('devices', '0006_alter_device_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device', verbose_name='Dispositivo'),
        ),
    ]
