# Generated by Django 5.2.7 on 2025-11-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('LAPTOP', 'Laptop'), ('TELEFONO', 'Teléfono Móvil'), ('TABLET', 'Tablet'), ('SIM', 'SIM Card'), ('ACCESORIO', 'Accesorio')], max_length=20, verbose_name='Tipo de equipo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie_imei', models.CharField(max_length=100, unique=True, verbose_name='Serie/IMEI')),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de factura')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Dado de Baja'), ('ROBO', 'Robo')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
