# Generated by Django 5.2.7 on 2025-12-11 20:09

from django.db import migrations, models


def migrate_serie_to_numero_serie(apps, schema_editor):
    """
    Migra los datos de serie_imei a numero_serie
    """
    Device = apps.get_model('devices', 'Device')
    for device in Device.objects.all():
        device.numero_serie = device.serie_imei
        device.save(update_fields=['numero_serie'])


def reverse_migrate_serie(apps, schema_editor):
    """
    Migración inversa: copia numero_serie de vuelta a serie_imei
    """
    Device = apps.get_model('devices', 'Device')
    for device in Device.objects.all():
        if device.numero_serie:
            device.serie_imei = device.numero_serie
            device.save(update_fields=['serie_imei'])


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        # PASO 1: Agregar nuevos campos (sin unique para permitir migración)
        migrations.AddField(
            model_name='device',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie'),
        ),
        migrations.AddField(
            model_name='device',
            name='imei',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IMEI'),
        ),
        migrations.AddField(
            model_name='device',
            name='edad_dispositivo',
            field=models.IntegerField(blank=True, help_text='Calculado automáticamente desde fecha_ingreso', null=True, verbose_name='Edad del dispositivo (años)'),
        ),
        migrations.AddField(
            model_name='device',
            name='valor_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de compra o tasación inicial', max_digits=10, null=True, verbose_name='Valor inicial (CLP)'),
        ),
        migrations.AddField(
            model_name='device',
            name='valor_depreciado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automáticamente o ingresado manualmente', max_digits=10, null=True, verbose_name='Valor depreciado (CLP)'),
        ),
        migrations.AddField(
            model_name='device',
            name='es_valor_manual',
            field=models.BooleanField(default=False, help_text='Indica si el valor depreciado fue ingresado manualmente', verbose_name='Valor manual'),
        ),

        # PASO 2: Migrar datos existentes de serie_imei a numero_serie
        migrations.RunPython(
            migrate_serie_to_numero_serie,
            reverse_migrate_serie
        ),

        # PASO 3: Agregar constraint unique a numero_serie e imei
        migrations.AlterField(
            model_name='device',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Serie'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='IMEI'),
        ),

        # PASO 4: Eliminar campo serie_imei
        migrations.RemoveField(
            model_name='device',
            name='serie_imei',
        ),

        # PASO 5: Actualizar choices de tipo_equipo para incluir TV
        migrations.AlterField(
            model_name='device',
            name='tipo_equipo',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('TELEFONO', 'Teléfono Móvil'), ('TABLET', 'Tablet'), ('TV', 'TV'), ('SIM', 'SIM Card'), ('ACCESORIO', 'Accesorio')], max_length=20, verbose_name='Tipo de equipo'),
        ),
    ]
