# Generated by Django 5.2.7 on 2025-12-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_device_serie_imei_device_edad_dispositivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
    ]
