# Generated by Django 5.2.7 on 2025-12-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_allow_blank_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='tipo_equipo',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Computadora de Escritorio'), ('TELEFONO', 'Teléfono Móvil'), ('TABLET', 'Tablet'), ('TV', 'TV'), ('SIM', 'SIM Card'), ('ACCESORIO', 'Accesorio')], max_length=20, verbose_name='Tipo de equipo'),
        ),
    ]
