# Generated by Django 5.2.7 on 2025-12-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_tipo_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Dado de Baja'), ('ROBO', 'Robo/Perdida')], default='DISPONIBLE', max_length=20, verbose_name='Estado'),
        ),
    ]
