# Generated by Django 5.2.7 on 2026-01-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_change_desktop_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el dispositivo está activo en el inventario', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='device',
            name='fecha_inactivacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el dispositivo fue marcado como inactivo', null=True, verbose_name='Fecha de inactivación'),
        ),
    ]
