# Generated by Django 5.2.7 on 2026-01-02 13:42

from django.db import migrations
from django.utils import timezone


def mark_final_state_devices_as_inactive(apps, schema_editor):
    """Marca como inactivos todos los dispositivos con estado BAJA o ROBO."""
    Device = apps.get_model('devices', 'Device')
    AuditLog = apps.get_model('users', 'AuditLog')

    final_states = ['BAJA', 'ROBO']
    inactive_devices = Device.objects.filter(estado__in=final_states)

    print(f"Encontrados {inactive_devices.count()} dispositivos en estados finales")

    for device in inactive_devices:
        # Buscar en auditoría cuándo se cambió a estado final
        audit_entry = AuditLog.objects.filter(
            entity_type='Device',
            entity_id=device.id,
            action='UPDATE',
            changes__field='estado',
            changes__new_value=device.estado
        ).order_by('-timestamp').first()

        if audit_entry:
            device.fecha_inactivacion = audit_entry.timestamp
        else:
            device.fecha_inactivacion = timezone.now()

        device.activo = False
        device.save(update_fields=['activo', 'fecha_inactivacion'])

    print(f"Marcados {inactive_devices.count()} dispositivos como inactivos")


def reverse_inactive_marking(apps, schema_editor):
    """Revierte la migración."""
    Device = apps.get_model('devices', 'Device')
    Device.objects.all().update(activo=True, fecha_inactivacion=None)


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_add_active_fields'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            mark_final_state_devices_as_inactive,
            reverse_inactive_marking
        ),
    ]
