# Generated by Django 5.2.7 on 2025-11-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('correo_corporativo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo corporativo')),
                ('gmail_personal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmail personal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('unidad_negocio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad de negocio')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
