# Generated by Django 5.2.7 on 2025-11-06 01:49

import apps.employees.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rut',
            field=models.CharField(help_text='Formato: XX.XXX.XXX-X o XXXXXXXX-X', max_length=12, unique=True, validators=[apps.employees.validators.validate_rut], verbose_name='RUT'),
        ),
    ]
