# Generated by Django 5.2.7 on 2025-12-27 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_rename_unidad_negocio_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.businessunit', verbose_name='Unidad de negocio'),
        ),
    ]
