# Generated by Django 6.0 on 2026-01-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_change_desktop_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el empleado está activo en el sistema', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='fecha_inactivacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el empleado fue marcado como inactivo (soft delete)', null=True, verbose_name='Fecha de inactivación'),
        ),
    ]
