# Generated by Django 5.2.7 on 2025-12-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='direccion',
        ),
    ]
